### PR TITLE
Opam file fix and cleanup

### PR DESCRIPTION
**Pull request by XVilka**
Added a missing dependencies on `conf-python-3` and `conf-aclocal`. Also removed the unnecessary remove directives.

See https://github.com/ocaml/opam-repository/pull/15687 for more information.

### CODE REVIEW

**Comment by fantazio** [comment]
Thanks for contributing.

How did you notice the missing dependencies ? Why are the remove directives unnecessary ?

I guess we can wait for https://github.com/ocaml/opam-repository/issues/15688 to be fixed before applying your changes

**Comment by XVilka** [comment]
@fantazio the opam-repository has a good CI with various Linux distributions, thus missing dependencies were caught on some of them, particularly Fedora, CentOS, and OpenSUSE. Directives were removed because they are not needed with the recent Dune and opam, the removal was requested by the main opam repository maintainer.
No need to wait for that issue to be fixed, since the PR with the updated opam file was merged in the repository. Please consider merging as-is.

**Comment by thierry-martinez** [comment]
LGTM. Thanks!

**Comment by XVilka** [comment]
@fantazio @JuliaLawall should it be merged then?

**Comment by fantazio** [comment]
Applied, thanks ;)

**Pull request closed without merging**
