### PR TITLE
Add support for BSD likelihood annotations

### PR DESCRIPTION
**Pull request by mmcco**
Coccinelle already supports Linux's likely() and unlikely(), but the
BSDs use __predict_true() and __predict_false() instead.

Signed-off-by: Michael McConville <mmcco@mykolab.com>

### CODE REVIEW

**Comment by JuliaLawall** [comment]
On Fri, 29 Jan 2016, Michael McConville wrote:

> 
> Coccinelle already supports Linux's likely() and unlikely(), but the
> BSDs use __predict_true() and __predict_false() instead.

Thank you for the suggestion.  However, the second line is the name of the 
rule, which should be unique.  Could you change it to something else.

+Expression
+@ unlikely @
+expression E;
+@@
+
+__predict_false(E) <=> __predict_true(E) => E

thanks,
julia

**Comment by mmcco** [comment]
Done. Thanks!

**Comment by shindere** [comment]
Merged. Thanks.

**Comment by elfring** [comment]
Would you like to consider the possibility once more to pass such an annotation isomorphism in another file by a command line parameter like "--iso-file"?

**Pull request closed without merging**
