### PR TITLE
Replacement should be done even the code has a dead part

### PR DESCRIPTION
**Pull request by sgwaki**
Hello,
Test in the pull request fails on spatch version 1.0.4. The replacement doesn't happen.
--debug shows `FLOW: deadcode detected: File "./deadcode.c", line 3`
I think it should be replaced even the code has a dead part.

Actual code is seen in Wine 2.7's dlls/shlwapi/url.c from line 707 to 874, https://source.winehq.org/source/dlls/shlwapi/url.c?v=wine-2.7#0707 .

### CODE REVIEW

**Comment by JuliaLawall** [comment]
On Sat, 13 May 2017, Akihiro Sagawa wrote:

>
> Hello,
> Test in the pull request fails on spatch version 1.0.4. The replacement doesn't happen.
> --debug shows FLOW: deadcode detected: File "./deadcode.c", line 3
> I think it should be replaced even in a deadcode.
>
> Actual code is seen in Wine 2.7's dlls/shlwapi/url.c from line 707 to 874, https://source.winehq.org/source/dlls/shlwapi/url.c?v=wine-2.7#0707 .

Thanks for the report.  I will have to look into it.  Currently, it is
just giving up on the function because it considers that the function
contains dead code.

Actually, I prefer not to receive pull requests.  It is easier to just
have the information available in the message.

julia

**Comment by sgwaki** [comment]
> Actually, I prefer not to receive pull requests. It is easier to just have the information available in the message.

I missed bugs.txt at the top directory. Sorry about that.
Should I mail the information to the list?

**Comment by JuliaLawall** [comment]
On Sat, 13 May 2017, Akihiro Sagawa wrote:

>
>       Actually, I prefer not to receive pull requests. It is easier to
>       just have the information available in the message.
>
> I missed bugs.txt at the top directory. Sorry about that.
> Should I mail the information to the list?

Perhaps it is a good idea.  Then others can be aware of the issue.

julia

**Comment by JuliaLawall** [comment]
On Sat, 13 May 2017, Akihiro Sagawa wrote:

>
> Hello,
> Test in the pull request fails on spatch version 1.0.4. The replacement
> doesn't happen.
> --debug shows FLOW: deadcode detected: File "./deadcode.c", line 3
> I think it should be replaced even in a deadcode.

Coccinelle aborts treatment of a function when it encunters deadcode.
This is an ancient feature, and I am a bit nervous about removing it.  I
wonder why you need the break before the while (0)?

julia

**Comment by sgwaki** [comment]
On Wed, 17 May 2017 07:03:26 -0700, JuliaLawall wrote:
> On Sat, 13 May 2017, Akihiro Sagawa wrote:
> > Hello,
> > Test in the pull request fails on spatch version 1.0.4. The replacement
> > doesn't happen.
> > --debug shows FLOW: deadcode detected: File "./deadcode.c", line 3
> > I think it should be replaced even in a deadcode.
> 
> Coccinelle aborts treatment of a function when it encunters deadcode.
> This is an ancient feature, and I am a bit nervous about removing it.  I
> wonder why you need the break before the while (0)?

There are three reasons why I keep the break line:
1) Because I'm not the original author. I'm not sure why he put the
break before the while (0). I'd rather not touch his code if possible. 
2) There are various coding styles in the world. Thus, removing the code
doesn't resolve another case.
3) In my opinion, this doesn't introduce deadcode at all.

I understand this is a difficult decision. So, how about considering break
before while(0) as harmless (= not a deadcide)? If this is archived, at
least, Coccinelle will be able to find a similar redundant break line
and remove the code.

Akihiro Sagawa

> julia

**Pull request closed without merging**
