### PR TITLE
make -> $(MAKE)

### PR DESCRIPTION
**Pull request by madroach**

### CODE REVIEW

**Comment by JuliaLawall** [comment]
Thanks for the commits.  However, they need a Signed-off-by.  See the end of coccinelle/readme.txt.
I would also prefer to get the commits by email, but if that is not convenient, then you can just update them here.

**Comment by npalix** [comment]
Looks good.

**Comment by madroach** [comment]
Thanks for having a look. I added the requested `Signed-off-by:` lines.

I got reports of build failures using those patches on OpenBSD. I may send some more commits in the next few days.

**Comment by JuliaLawall** [comment]
@madroach what is the status of this pull request?  Are you still getting build failures?

**Comment by madroach** [comment]
I did not yet have time to further investigate those reports, but it works for me so far. You might as well merge this pull request. I can always open another in case I figure out other changes are necessary.

**Comment by JuliaLawall** [comment]
I have propagated this to our internal development system.

**Pull request closed without merging**
