### PR TITLE
Add a dockerfile to build coccinelle Ububtu 16.04 Docker image 

### PR DESCRIPTION
**Pull request by w-simon**
Coccinelle has a lot of dependencies, and it is cumbersome to set up its environment.
We solved this problem by packaging coccinelle and its dependencies into a lightweight, portable container.

### CODE REVIEW

**Comment by JuliaLawall** [comment]
On Sun, 31 Mar 2019, Wen Yang wrote:

>
> Coccinelle has a lot of dependencies, and it is cumbersome to set up its
> environment.
> We solved this problem by packaging coccinelle and its dependencies into a
> lightweight, portable container.

Is this more useful than the Ubuntu PPA?

https://launchpad.net/~npalix/+archive/ubuntu/coccinelle

Thierry, can you check that everything is ok here?

thanks,
julia

**Comment by thierry-martinez** [comment]
A benefit of this Dockerfile compared to the PPA is that it compiles Coccinelle master rather than the last packaged release. However, the usual way to declare external dependencies for OCaml software is via an opam file (and opam depext): this would allow to declare such dependencies only once and that would work both for docker container or for a direct installation on the host.

**Comment by w-simon** [comment]
Thank you. Another benefit of this Dockerfile is that it can build cross-platform images. So we can run this coccinell container on various operating systems such as ubuntu, fedora, centos, etc.

**Comment by thierry-martinez** [comment]
I just committed a `Dockerfile` which uses opam to install coccinelle and its dependencies. The recipies should be distribution independent.

**Comment by JuliaLawall** [comment]
On Wed, 10 Apr 2019, thierry-martinez wrote:

>
> I just committed a Dockerfile which uses opam to install coccinelle and its
> dependencies. The recipies should be distribution independent.

Super!  Thanks.

julia

**Comment by w-simon** [comment]
Very good, thanks！

**Pull request closed without merging**
