### PR TITLE
Issue #189: Remove PyImport_Cleanup() wrapper

### PR DESCRIPTION
**Pull request by vstinner**
PyImport_Cleanup() was documented as: "Empty the module table. For
internal use only." in Python 3.8. The function was removed in Python
3.9. It wasn't used in coccinelle anyway.

### CODE REVIEW

**Comment by vstinner** [comment]
I didn't test my PR. I never used Coccinelle and I don't know how to test it. I only used "grep" in the code and removed any reference to PyImport_Cleanup() :-)

The wrapper was added by a change which exposes tons of Python functions:

```
commit 62f2df8c7d35967a1eca4dcd487d59a9918dd5aa
Author: Thierry Martinez <martinez@nsup.org>
Date:   Sun Jun 26 20:22:59 2016 +0200

    Fixed: Bundles compilation and pyml update
    
    - %.cmx: %.cmo dependency (with .ml files that do not have .mli,
      compiling the .ml into .cmo or into .cmx both write to the same .cmi
      file, so that cannot be done concurrently)
    - untarred pyml distribution to ease updates
    - Python exception catched in pycocci interface
```

**Comment by rwmjones** [comment]
You'll need to at least remove `val cleanup: unit -> unit` since what you removed was a comment which documents this API.  And then in the corresponding implementation file there is: `let cleanup = Pywrappers.pyimport_cleanup` which will also need to be removed.  And then that is actually a call to `pyimport_cleanup` (see pycaml.mli), and I think the implementation of that is generated somewhere, but I'm not sure where.

**Comment by vstinner** [comment]
> You'll need to at least remove val cleanup: unit -> unit

Oh, I missed "pyimport_cleanup". I removed it in my second commit.

**Comment by rwmjones** [comment]
With the proviso that I'm using Python 3.8 (not 3.9) your patch does compile for me.  After compiling `find -type f | xargs grep PyImport_Cleanup` returns nothing, so that indicates to me that there's a good chance `PyImport_Cleanup` is no longer being used.

So I would say this patch looks good to me.

**Comment by JuliaLawall** [comment]
This is in the pyml bundle.  Has the problem been reported there as well?

https://github.com/thierry-martinez/pyml

I have sent a message to Thierry about it.

julia

**Comment by rwmjones** [comment]
I don't believe it was reported upstream, so thanks.

**Comment by vstinner** [comment]
Oh, I didn't notice that coccinelle bundles pyml.

I reported the issue to pyml: https://github.com/thierry-martinez/pyml/issues/49

I proposed a PR for pyml: https://github.com/thierry-martinez/pyml/pull/50

**Comment by thierry-martinez** [comment]
This issue has been fixed upstream (https://github.com/thierry-martinez/pyml/commit/8b26fdb9f60c3a66b58f2ecc1b2136a833f55612). In Coccinelle bundles, `PyImport_Cleanup` is optional since 455cf5f25 and `Py.Import.cleanup` has been removed since e2e4757cc.

**Pull request closed without merging**
